project:
  name: primary
  preserve_unused_resources: 1
  nodes:
    inclusion-awu:
      roles: [manager]
      labels:
        ingress: "true"
        swarmcp.volume.core.ingress: "true"
        swarmcp.volume.core.portainer: "true"
      volumes:
        - core.ingress
        - core.portainer
      platform:
        os: linux
        arch: amd64
    inclusion-nuc:
      roles: [manager]
      platform:
        os: linux
        arch: amd64
    inclusion-sa:
      roles: [manager]
      platform:
        os: linux
        arch: amd64
  secrets_engine:
    provider: bao
    addr: https://10.10.1.7:8200
    auth:
      method: approle
    vault:
      mount: kv
      path_template: "{project}/{partition}/{stack}/{service}"
  partitions: [dev, qa]
  deployments: [nonprod, prod]
  deployment: nonprod
  contexts:
    nonprod: default
    prod: default
  configs:
    ca_chain:
      source: templates/configs/ca_chain.pem
      target: /etc/ssl/certs/ca-chain.pem
    vault_url:
      source: values#/vault_url
    domain:
      source: values#/domain
    ip_whitelist:
      source: values#/ip_whitelist
  deployment_targets:
    nonprod:
      include:
        names:
          - inclusion-awu
          - inclusion-nuc
          - inclusion-sa
    prod:
      include:
        names:
          - inclusion-awu
          - inclusion-nuc
          - inclusion-sa
  defaults:
    networks:
      shared:
        - "{project}_core"
    volumes:
      driver: local
      base_path: /srv/data
      node_label_key: swarmcp.volume
      service_standard: persist
      service_target: /data
      standards:
        host:
          source: /
          target: /host
          readonly: false
        docker_volumes:
          source: /var/lib/docker/volumes
          target: /var/lib/docker/volumes
          readonly: false
        docker_sock:
          source: /var/run/docker.sock
          target: /var/run/docker.sock
          readonly: true
          requires:
            roles: [ manager ]
overlays:
  deployments:
    nonprod:
      project:
        configs:
          ca_chain:
            source: templates/configs/ca_chain.pem
            target: /etc/ssl/certs/ca-chain.pem
    prod:
      project:
        configs:
          ca_chain:
            source: templates/configs/ca_chain.pem
            target: /etc/ssl/certs/ca-chain.pem
  partitions:
    dev:
      project:
        configs:
          ip_whitelist:
            source: values#/ip_whitelist
            target: /etc/traefik/ip_whitelist_dev
    qa:
      project:
        configs:
          ip_whitelist:
            source: values#/ip_whitelist
            target: /etc/traefik/ip_whitelist_qa
stacks:
  core:
    configs:
      domain:
        source: values#/domain
      log_level:
        source: values#/log_level
    mode: shared
    services:
      agent:
        image: chrismoran/infamousity:portainer.-agent__2.33.6
        egress: true
        env:
          AGENT_CLUSTER_ADDR: tasks.agent
          LOG_LEVEL: DEBUG
        ports:
          - target: 9001
            published: 9001
            protocol: tcp
            mode: host
        volumes:
          - standard: docker_sock
          - standard: docker_volumes
          - standard: host
        mode: global
        placement:
          constraints:
            - node.platform.os == linux
        labels:
          traefik.enable: "false"
      portainer:
        image: chrismoran/infamousity:portainer.-portainer-ee__2.33.6
        args:
          - -H
          - tcp://tasks.agent:9001
          - --tlsskipverify
        egress: true
        volumes:
          - standard: persist
            target: /data
          - standard: docker_sock
        replicas: 1
        labels:
          traefik.enable: "true"
          traefik.http.routers.portainer.entrypoints: websecure
          traefik.http.routers.portainer.middlewares: google-oidc@file
          traefik.http.routers.portainer.rule: {{ printf "Host(`m.%s`)" (config_value_index "domain" 0) }}
          traefik.http.routers.portainer.service: portainer
          traefik.http.routers.portainer.tls: "true"
          traefik.http.services.portainer.loadbalancer.server.port: "9000"
          traefik.swarm.network: {{ runtime_value `{project}_{stack}` }}
      ingress:
        image: chrismoran/infamousity:traefik__v3.6.7e
        egress: true
        mode: global
        env:
          CF_DNS_API_TOKEN_FILE: {{ secret_ref "cf_dns_api_token" }}
          CF_ZONE_API_TOKEN_FILE: {{ secret_ref "cf_dns_api_token" }}
          VAULT_LOCK_ID: {{ escape_swarm_template ".Service.Name" }}.{{ escape_swarm_template ".Task.Slot" }}
        labels:
          traefik.enable: "false"
          traefik.swarm.lbswarm: "true"
        volumes:
          - source: /var/log/traefik
            target: /var/log
            readonly: false
          - standard: docker_sock
          - standard: persist
            target: /etc/geoip
        ports:
          - target: 80
            published: 80
            mode: host
          - target: 443
            published: 443
            mode: host
          - target: 54333
            published: 54333
            mode: host
        configs:
          - name: domain
          - name: ca_chain
            target: /etc/ssl/certs/ca-chain.pem
          - name: vault_client_crt
            source: templates/stacks/core/services/ingress/configs/vault_client.crt
            target: /vault_client.crt
          - name: traefik_yml
            source: templates/stacks/core/services/ingress/configs/traefik.yml.tmpl
            target: /etc/traefik/traefik.yml
          - name: dynamic_yml
            source: templates/stacks/core/services/ingress/configs/dynamic.yml.tmpl
            target: /etc/traefik/dynamic.yml
          - name:  google_oidc_client_id
            source: values#/google_oidc_client_id
          - name: google_oidc_valid_email
            source: values#/google_oidc_valid_email
        secrets:
          - name: api_key_values
          - name: vault_client_key
            target: /run/secrets/vault_client.key
          - name: cf_dns_api_token
          - name: google_oidc_client_secret

  ext:
    mode: shared
    services:
      fpng:
        image: chrismoran/infamousity:fpng-web__v0.0.1
        replicas: 1
        ports:
          - mode: ingress
            target: 3000
        labels:
          traefik.enable: "true"
          traefik.http.routers.fpng.entrypoints: websecure
          traefik.http.routers.fpng.middlewares: inject-geoip@file,google-oidc@file
          traefik.http.routers.fpng.rule: {{ printf "Host(`fpng.%s`)" (config_value_index "domain" 0) }}
          traefik.http.routers.fpng.tls: "true"
          traefik.http.services.fpng.loadbalancer.server.port: "3000"
          traefik.swarm.network: {{ runtime_value `{project}_core` }}
      jls:
        image: chrismoran/infamousity:jls__v1.0.6
        replicas: 1
        ports:
          - mode: ingress
            target: 8080
        labels:
          traefik.enable: "true"
          traefik.http.routers.jls.entrypoints: websecure
          traefik.http.routers.jls.middlewares: inject-geoip@file
          traefik.http.routers.jls.rule: {{ printf "Host(`jls.%s`)" (config_value_index "domain" 0) }}
          traefik.http.routers.jls.tls: "true"
          traefik.http.services.jls.loadbalancer.server.port: "8080"
          traefik.swarm.network: {{ runtime_value `{project}_core` }}
      whoami:
        image: traefik/whoami:v1.10.1
        replicas: 1
        labels:
          traefik.enable: "true"
          traefik.http.routers.whoami.rule: {{ printf "Host(`whoami.%s`)" (config_value_index "domain" 0) }}
          traefik.http.routers.jls.middlewares: inject-geoip@file,google-oidc@file
          traefik.http.routers.whoami.entrypoints: websecure
          traefik.http.routers.whoami.tls: "true"
          traefik.http.services.whoami.loadbalancer.server.port: "80"
